import libs = cli11%lib{cli11}
import libs += catch2%lib{catch2}

./: exe{cli11-tests} doc{README.md} manifest

unsupported_tests = tests/mesonTest/* tests/WindowsTest tests/BoostOptionTypeTest tests/informational tests/SubcommandTest

exe{cli11-tests}: {hxx cxx}{** -{$unsupported_tests}} $libs

# Only add WindowsTest for windows.
exe{cli11-tests}: tests/cxx{WindowsTest}: include = ($cxx.target.class == 'windows')

exe{cli11-tests}: test.options = "~Validators: DirectoryExists" "~Validators: CombinedPaths" "~Validators: PathExistsDir" "~Types: LexicalCastParsable"

if ($cxx.class == 'msvc')
{
    cxx.coptions += /wd4996
}
else
{
    cxx.coptions += -Wno-deprecated-declarations
}
