import libs  = cli11%lib{cli11}
import libs += catch2%lib{catch2}

tests = \
  HelpersTest \
  ConfigFileTest \
  OptionTypeTest \
  SimpleTest \
  AppTest \
  SetTest \
  TransformTest \
  CreationTest \
  SubcommandTest \
  HelpTest \
  FormatterTest \
  NewParseTest \
  OptionalTest \
  DeprecatedTest \
  StringParseTest \
  ComplexTypeTest \
  TrueFalseTest \
  OptionGroupTest

if ($cxx.target.class == 'windows')
    tests += WindowsTest

for t: $tests
{
    ./: exe{$t}: tests/cxx{$t} tests/hxx{app_helper catch} tests/cxx{main} $libs
}

exe{HelpersTest}: test.options = \
    "~Validators: DirectoryExists" "~Validators: CombinedPaths" "~Validators: PathExistsDir"

exe{OptionTypeTest}: testscript{option_type.test}
